import { Hero } from '@/components/Hero';
import { About } from '@/components/About';
import { Contact } from '@/components/Contact';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Local } from '@/components/Local';
import { Packages } from '@/components/Packages';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Shotter Paintball</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <About />
        <Local />
        <Packages />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
